Four main types ofnoxious stimuli are common causes of
pulpal inflammation (pulpitis): 1. Mechanicaldamage: Mechanical sources ofinjury include traumatic accidents, iatrogenic damage from dental procedures, attrition, abrasion, and barometric changes.
1. Thermalinjury: Severe thermal stimuli can be transmitted through large uninsulated metallic restorations or may occur from such dental procedures as cavity preparation, polishing, and exothermic chemical reactions of dental materials.
2. Chemical irritation: Chemical-related damage can arise from erosion or from the inappropriate use ofacidic dental materials.
3. Bacterial effects: Bacteria can damage the pulp through toxins or directly after extension from caries or transportation via the vasculature.










Most cases of pulpitis are primarily a result of **dental caries** in which bacteria or their products invade the dentin and pulp tissue. Dental caries is usually obvious unless it extends under the edge of a restoration
Occasionally, there is bacterial invasion in the absence of caries, as
in cases of **tooth fracture** due to trauma or **cracked tooth syndrome** that expose the dental pulp to the oral environment. In cracked tooth syndrome, a tooth, usually a restored premolar, may split under masticatory stress. These cracks are often minute and invisible clinically, and they allow the bacteria to enter into the pulp (see the colored box below

Bacterial invasion may also occur as a result of a bacteremia and
septicemia. Pulpitis may rarely follow chronic periodontal disease, wherein the microorganisms enter through the accessory canals of the exposed root surface especially through lateral canals in **furcation** areas of molars. The significance of microorganisms in the etiology of pulpitis has
been confirmed by many studies. It was found that no devitalized pulps or periapical infections developed, when surgical pulp exposure was made in germ-free rats even when gross food impactions existed. By contrast, conventional animals rapidly developed complete pulpal necrosis. Pulpitis may also arise as a result of chemical irritation of the pulp
caused by **erosion** or use of acidic restorative materials. This may occur not only in an exposed pulp to which some irritating medicament is applied but also in intact pulps beneath deep or moderately deep cavities into which some irritating filling material is inserted. This is undoubtedly a result of penetration of the irritating substances into the pulp via the dentinal tubules. In many instances, however, the pulp may respond to the irritation either by dentinal sclerosis or by forming reparative dentin rather than progressing to pulpitis. Severe thermal change in a tooth may also produce pulpitis.
Polishing procedures, tooth restored with exothermic restorative materials, or large metallic restorations, particularly, in which there is inadequate insulation between the restoration and the pulp are more prone to pulpal inflammation.

Heat produced by overrapid tooth preparation or without sufficient
coolant may also cause pulpal irritation. Heat and, more particularly, cold are transmitted to the pulp, often producing pain and if the stimulus is prolonged and severe, leading to actual pulpitis. Mild thermal changes are most apt to stimulate only the formation of reparative dentin, and this is a relatively common phenomenon. When two dissimilar metallic restorations are present, the saliva
acts as an electrolyte and there will be formation of a galvanic current. This may be transmitted to the pulp through metallic restoration and may thus initiate pulpitis. It is apparent that pulpitis may be caused by a variety of
circumstances and the nature of the etiologic agent or agents can usually be found through study of the clinical or microscopic features of the condition or both.




= Focal reversible pulpitis

One of the earliest forms of pulpitis is the condition known as focal reversible pulpitis . At one time, this was often referred to as pulp hyperemia . However, it is known that vascular dilatation can occur artifactually from the “pumping” action during tooth extraction as well as pathologically as a result of dentinal and pulpal irritation. Therefore, this early mild transient pulpitis, localized chiefly to the pulpal ends of irritated dentinal tubules, is now known as focal reversible pulpitis.




# clinical findings 
A tooth with focal pulpitis is sensitive to thermal changes, particularly to cold. The application of ice or cold fluids to the tooth results in pain, but this disappears upon removal of the thermal stimuli or restoration of the normal temperature. It will be found also that such a tooth responds to stimulation by the electric pulp tester at a lower level of current, indicating a lower pain threshold (or a greater sensitivity) than that of adjacent normal teeth. Teeth in which this condition exists usually show deep carious lesions, large metallic restorations (particularly, without adequate insulation), or restorations with defective margins.


# treatment 
Focal pulpitis is generally regarded as a reversible condition, provided the irritant is removed before the pulp is severely damaged. Thus, a carious lesion should be excavated and restored or a defective filling replaced as soon as it is discovered. If the primary cause is not corrected, extensive pulpitis eventually results, with subsequent “death” of the pulp.


= Acute pulpitis
Extensive acute inflammation of the dental pulp is a frequent immediate sequela of focal reversible pulpitis, although it may also occur as an acute exacerbation of a chronic inflammatory process. Significant differences in both clinical and microscopic features are found between acute and chronic pulpitis.

# clinical findings 
Characteristically, this pain persists even after the thermal stimulus has disappeared or been removed.


As a greater proportion of the pulp becomes involved with intrapulpal abscess formation, the pain may become even more severe and is often described as lancinating or throbbing type. The pain generally lasts for 10–15 minutes but may be more or less continuous,

The pulpal pain is caused by not only the pressure built-up due to lack of escape of inflammatory exudates but also the pain producing substances released by the inflammatory reaction. 

Severe pain is more likely to be present when the entrance to the diseased pulp is not wide open.When a large open cavity is present, there is no opportunity for a buildup of pressure. Thus, the inflammatory process does not tend to spread rapidly throughout the pulp. In such a case the pain experienced by the patient is a dull, throbbing ache, but the tooth is still sensitive to thermal changes. Mobility and sensitivity to percussion are usually absent.


presence of etiology consequence
narrow cavity
pain = even after thermal, severe,lanching,throbbing,duration 10 min but continous

wide cavity
pain = dull,throbbing,sensitive,more thermal

= Chronic pulpitis

Chronic pulpitis may arise on occasion through quiescence of a previous acute pulpitis, but more frequently it occurs as the chronic type of disease from the onset. 

# clinical findings 
Pain is not a prominent feature of chronic pulpitis, although sometimes the patient complains of a mild, dull ache, which is more often intermittent than continuous. The reaction to thermal change is dramatically reduced in comparison to that in acute pulpitis. Because of the degeneration of nerve tissue in the affected pulp


The general features of chronic pulpitis are not distinctive, and serious involvement of the pulp may be present in the absence of significant symptoms. Even in cases of chronic pulpitis with wide-open carious lesions and with exposure of the pulp to the oral environment, there is relatively little pain. The exposed pulp tissue may be manipulated by a small instrument, but though bleeding may occur, pain is often absent and pulps may become totally necrotic without pain.

pain = No but may mild, dull ache,intermittent than continuous,reduced

= Chronic hyperplastic pulpitis
Also known as pulp polyp

Chronic hyperplastic pulpitis is a unique form of pulpitis wherein the inflamed pulp, instead of perishing by continued suppuration, reacts by excessive and exuberant proliferation. It occurs either as a chronic lesion from the onset or as a chronic stage of a previously acute pulpitis.

# clinical findings 
Chronic hyperplastic pulpitis occurs almost exclusively in children and young adults who possess a high degree of tissue resistance and reactivity, and readily respond to proliferative lesions

It involves teeth with large, open carious lesions. A pulp so affected appears as a pinkish-red globule of tissue protruding from the pulp chamber and not only fills the caries defect but also extends beyond (Figure 12.7 ). Since the hyperplastic tissue contains few nerves, it is relatively insensitive to manipulation. The lesion may or may not bleed readily, depending on the degree of vascularity and epithelialization.


The teeth most commonly involved by this phenomenon are the deciduous molars and the first permanent molars. These have an excellent blood supply because of the large root opening, and this coupled with the high tissue resistance and reactivity in young persons, accounts for the unusual proliferative property of the pulp tissue.



Rootstumps
