= Definition.
Strong eccentric occlusal force resulting in microfractures at the cervical area of the tooth causing wedgeshaped defects is termed as abfraction (Fig. 20.5).4

= Etiology
Teeth are not rigid structures and undergo deformation (strain) during normal loading.5 Intra-oral loads (forces) vary widely and have been reported to range from 10 N to 431 N, with a functional load of 70 N considered clinically normal.6 The number of teeth, type of occlusion and occlusal habits of patients (e.g. bruxism) affect the load per tooth. Abfraction is caused due to tooth flexure in patients with abnormal occlusal interactions. The mechanism is explained in Box 20.1.
Clinical Features I.
These lesions are characterized by sharp notch or wedgeshaped lesions instead of the saucer-shaped defects associated with other non-carious cervical lesions.
II. The maximal abfractive stresses generated are at the cervical area in the thinnest region of enamel at the cementoenamel junction (CEJ) (Figs. 20.6 and 20.7).7–11
III. These forces can also cause the loss of bonded Class V restorations in preparations with no retention grooves (Fig. 20.8).

IV. Such fractures predispose enamel to loss when subjected to toothbrush abrasion and chemical erosion. This process may act as a key in the formation of some Class V defects. Additionally, in unbonded or leaking resto-..
rations, this flexure of dentin may produce changes in fluid flow and microleakage, leading to sensitivity and pulpal inflammation.


= differential diagnosis
abrasion




Treatment of Abrasion, Erosion, Abfraction and Attrition
The primary goal of management should be to halt or modify the etiology of the problem. Box 20.2 enumerates