White
Red



Papules
Vesicles 


Solitary






2. WHITE LESIONS
Flat Plaques, Solitary 11 FRICTIONAL BENIGN KERATOSES 11 LEUKOPLAKIA 12 ACTINIC CHEILITIS 14 SMOKELESS TOBACCO KERATOSES 14 SANGUINARIA-INDUCED KERATOSES 16 DYSKERATOSIS CONGENITA 17 FANCONI’S ANEMIA 18 DYSPLASIA, CARCINOMA IN SITU, SQUAMOUS CELL CARCINOMA, AND VERRUCOUS CARCINOMA 19
LICHEN PLANUS (HYPERTROPHIC TYPE) 21 MUCOUS PATCHES (SECONDARY SYPHILIS) 22
Flat Plaques, Bilateral or Multifocal 23
LEUKOEDEMA 23 GENOKERATOSES 24
PLAQUE-FORM LICHEN PLANUS (SEE ABOVE) 30
CHEEK/TONGUE BITE KERATOSIS 30 Verrucous/Rippled Plaques 31
PROLIFERATIVE VERRUCOUS LEUKOPLAKIA 31 VERRUCOUS CARCINOMA 33
Lacey White Lesions 34 LICHEN PLANUS 34 LICHENOID REACTIONS 36 LUPUS ERYTHEMATOSUS 37 HIV-ASSOCIATED HAIRY LEUKOPLAKIA 38 Papular Lesions 40 KOPLIK SPOTS OF MEASLES 40 FORDYCE’S GRANULES 41
DENTAL LAMINA CYSTS, BOHN’S NODULES, EPSTEIN’S PEARLS 41
STOMATITIS NICOTINA 42 SPECKLED LEUKOPLAKIA 43
Pseudomembranous Lesions 44 CHEMICAL BURNS 44
CANDIDIASIS (MONILIASIS, THRUSH) 45 VESICULO-BULLOUS-ULCERATIVE DISEASES 47

3. RED AND PIGMENTED LESIONS Focal Erythemas 51
NONSPECIFIC (IRRITATIONAL) MUCOSITIS 51
MEDIAN RHOMBOID GLOSSITIS 52 HEMANGIOMA 53 VARIX 54 ERYTHROPLAKIA 55
Diffuse and Multifocal Red Lesions 56
GEOGRAPHIC TONGUE (MIGRATORY GLOSSITIS) 56
ERYTHEMA MIGRANS (MIGRATORY STOMATITIS) 57
ATROPHIC GLOSSITIS 58 RADIATION MUCOSITIS 59 XEROSTOMIC MUCOSITIS 60 LUPUS ERYTHEMATOSUS 61 ALLERGIC MUCOSITIS, FOREIGN BODY GINGIVITIS 63
BULLOUS/EROSIVE DISEASES 64 CANDIDIASIS 65 LYMPHONODULAR PHARYNGITIS 67 SCARLET FEVER 67 ATROPHIC LICHEN PLANUS 68 ECCHYMOSIS AND CLOTTING FACTOR DEFICIENCIES 70
FIELD CANCERIZATION 71 KAPOSI’S SARCOMA 72
49 Petechiae 73
SUCTION PETECHIAE 73 INFECTIOUS MONONUCLEOSIS 74 THROMBOCYTE DISORDERS 75 HEREDITARY HEMORRHAGIC TELANGIECTASIA 76
Focal Pigmentations 77 AMALGAM AND GRAPHITE TATTOO 77 MUCOCELE 78 HEMATOMA 79 NEVUS 80 EPHELIS, ORAL MELANOTIC MACULE 81
Diffuse and Multifocal Pigmentations 82 MALIGNANT MELANOMA 82 RACIAL PIGMENTATION 83 PIGMENTED LICHEN PLANUS 84 PEUTZ-JEGHERS SYNDROME 85 MULTIPLE NEUROFIBROMATOSIS 86 ADDISON’S DISEASE 87 HEMOCHROMATOSIS 88 HIV-ASSOCIATED ORAL PIGMENTATION 89
HEAVY METAL INGESTION 90 DRUG-INDUCED PIGMENTATION 91 HAIRY TONGUE


4. ORAL ULCERATIONS AND FISTULAE
Recurrent and Multiple Ulcerations 96
APHTHOUS STOMATITIS 96
MAJOR SCARRING APHTHOUS STOMATITIS 97 BEHÇET’S SYNDROME 99 GLUTEN ENTEROPATHY 100 AGRANULOCYTOSIS AND IMMUNOSUPPRESSION 100
CYCLIC NEUTROPENIA 101 UREMIC STOMATITIS 102 VIRAL VESICULAR STOMATITIS 103
ACUTE NECROTIZING ULCERATIVE GINGIVITIS 105
ACUTE STREPTOCOCCAL/ STAPHYLOCOCCAL STOMATITIS 106
CHRONIC ULCERATIVE STOMATITIS 107 GONOCOCCAL STOMATITIS 107 HIV PERIODONTITIS AND ORAL ULCERATIONS 108
Focal Ulcerations 109 TRAUMATIC ULCER 109
TRAUMATIC GRANULOMA WITH STROMAL EOSINOPHILIA 111


ATYPICAL HISTIOCYTIC GRANULOMA 112 NECROTIZING SIALOMETAPLASIA 113 SPECIFIC GRANULOMATOUS ULCER 114 CHANCRE (PRIMARY SYPHILIS) 115 SQUAMOUS CELL CARCINOMA 116 Perioral and Commissural Ulcerations and Fistulae 117 COMMISSURAL PITS 117 CONGENITAL LIP PITS 118 ANGULAR CHEILITIS 119 Oral Fistulae 120 PERIAPICAL ABSCESS AND OSTEOMYELITIS 120
PERIODONTAL ABSCESS 121 ACTINOMYCOSIS 122
OROANTRAL FISTULA 122 SOFT TISSUE ABSCESS 123 DEVELOPMENTAL ORAL SINUSES 124 FISSURED (SCROTAL) TONGUE 125
Necrotic and Osseous Destructive Lesions 126 FACTITIAL INJURY AND TRAUMA 126 WEGENER’S GRANULOMATOSIS 127 EXTRANODAL NK/T-CELL LYMPHOMA 128 TERTIARY SYPHILIS 129 OSTEORADIONECROSIS 130 MUCORMYCOSIS 131 ANTRAL CARCINOMA 132 BISPHOSPHONATE-RELATED OSTEONECROSIS OF THE JAWS 133

5. VESICULOBULLOUS AND DESQUAMATIVE LESIONS
Febrile-Associated Vesicular Eruptions 139 HERPETIC GINGIVOSTOMATITIS 139 HERPANGINA 140 HAND-FOOT-AND-MOUTH DISEASE 141 PRIMARY VARICELLA-ZOSTER (CHICKENPOX) 143
SECONDARY VARICELLA-ZOSTER (SHINGLES) 144
Nonfebrile-Associated Vesicular Eruptions 145
RECURRENT HERPES STOMATITIS 145 RECURRENT HERPES LABIALIS 146 CONTACT VESICULAR STOMATITIS 148 IMPETIGO 149
Bullous Diseases 150 PEMPHIGUS VULGARIS 150
BULLOUS PEMPHIGOID 151 BENIGN MUCOUS MEMBRANE PEMPHIGOID 152
BULLOUS LICHEN PLANUS 154 ERYTHEMA MULTIFORME 155 STEVENS-JOHNSON SYNDROME 156 PARANEOPLASTIC PEMPHIGUS 157 ANGINA BULLOSA HEMORRHAGICA 158 EPIDERMOLYSIS BULLOSA 159 DERMATITIS HERPETIFORMIS (GLUTEN ENTEROPATHY) 161
Desquamative Lesions 161
GINGIVOSIS (DESQUAMATIVE GINGIVITIS) 161
EROSIVE LICHEN PLANUS 163 LICHENOID CONTACT STOMATITIS 164 CHRONIC ULCERATIVE STOMATITIS 165 PYOSTOMATITIS VEGETANS 166 TOOTHPASTE IDIOSYNCRATIC LESIONS 168

6. INTRAORAL SOFT TISSUE SWELLINGS 171
Localized Gingival Tumefactions 173 PARULIS 173 PYOGENIC GRANULOMA 175
PERIPHERAL GIANT CELL GRANULOMA 176 PERIPHERAL FIBROMA 177 GIANT CELL FIBROMA 178 PERIPHERAL OSSIFYING FIBROMA 179
JUVENILE SPONGIOTIC GINGIVAL HYPERPLASIA 180
RETROCUSPID PAPILLAE 181 TORUS MANDIBULARIS AND EXOSTOSES 181 GINGIVAL CYST 183 ERUPTION CYST 184 EPULIS FISSURATA 185 CONGENITAL EPULIS 185 MESENCHYMAL TUMORS 187 PERIPHERAL ODONTOGENIC TUMORS 188 SQUAMOUS CELL CARCINOMA 189 SARCOMAS 190 MUCOEPIDERMOID CARCINOMA 191 NON-HODGKIN’S LYMPHOMA 192 METASTATIC CARCINOMA 193 LANGERHANS CELL HISTIOCYTOSIS 194
Generalized Gingival Swellings 195 FIBROMATOSIS GINGIVAE 195 DRUG INDUCED HYPERPLASIA 196 NONSPECIFIC HYPERPLASTIC GINGIVITIS 197
WEGENER’S GRANULOMATOSIS 198 TYPE I DIABETES MELLITUS 199 PUBERTY/PREGNANCY GINGIVITIS 200 LEUKEMIA 201
Swellings of the Oral Floor 202 RANULA AND SIALOCYSTS 202 DISONTOGENIC CYSTS 203 LYMPHOEPITHELIAL CYST 204 SIALOLITHIASIS WITH SIALADENITIS 205 SALIVARY GLAND TUMORS 207 ADENOMATOID HYPERPLASIA 207 MESENCHYMAL NEOPLASMS 208 LUDWIG’S ANGINA 209 SQUAMOUS CELL CARCINOMA 210 Swellings of the Lips and Buccal Mucosa 211
MUCOUS RETENTION (EXTRAVASATION) PHENOMENON (MUCOCELE) 211
SIALOCYST 213 MINOR GLAND SIALOLITHIASIS 214 NASOALVEOLAR (KLESTADT) CYST 215 CHEILITIS GRANULOMATOSA 216
CHEILITIS GLANDULARIS 217 ANGIONEUROTIC EDEMA 218 ACTINIC PRURIGO 219 INFLAMMATORY FIBROUS HYPERPLASIA 220 FOREIGN BODY GRANULOMA 220 CROHN’S DISEASE 221 TRAUMATIC FIBROMA 222 TRAUMATIC (AMPUTATION) NEUROMA 224 MESENCHYMAL NEOPLASMS 224 HERNIATED BUCCAL FAT PAD 225 REACTIVE LYMPHOID HYPERPLASIA 226 HEMANGIOMA AND VARIX 227 SQUAMOUS CELL CARCINOMA 229 MONOMORPHIC ADENOMA 230 OTHER SALIVARY NEOPLASMS 231
Tongue Swellings 232 MEDIAN RHOMBOID GLOSSITIS 232 ECTOPIC LINGUAL THYROID 233 THYROGLOSSAL DUCT CYST 234
LINGUAL CYST (ENTEROCYSTOMA, GASTRIC CYST) 235
HYPERPLASTIC LINGUAL TONSIL 236 LINGUAL ABSCESS 237
REACTIVE LESIONS (FIBROMA, PYOGENIC GRANULOMA) 237
MUCOCELE 238 HEMANGIOMA AND LYMPHANGIOMA 239 NEURAL SHEATH TUMORS 241 GRANULAR CELL TUMOR 242 LEIOMYOMA 243 OSTEOCARTILAGINOUS CHORISTOMA 244 ECTOMESENCHYMAL CHONDROMYXOID TUMOR 245 SARCOMAS 245 AMYLOID NODULES 246 SPECIFIC GRANULOMA 247 SQUAMOUS CELL CARCINOMA 248 Palatal Swellings 250 TORUS PALATINUS 250 CYST OF THE INCISIVE PAPILLA 251 PALATAL ABSCESS 251 REACTIVE LESIONS OF PALATAL GINGIVAL 252 ADENOMATOUS HYPERPLASIA 252 PLEOMORPHIC ADENOMA 253
POLYMORPHOUS LOW-GRADE ADENOCARCINOMA 254
MISCELLANEOUS ADENOCARCINOMAS 255 ADENOID CYSTIC CARCINOMA 256 MUCOEPIDERMOID CARCINOMA 258
ADENOCARCINOMA, NOS 259 ATYPICAL LYMPHOPROLIFERATIVE DISEASE 259
SQUAMOUS CELL CARCINOMA 261 CARCINOMA OF THE ANTRUM 262






= Reference 
CLINICAL OUTLINE OF ORAL PATHOLOGY: DIAGNOSIS AND TREATMENT FOURTH EDITION Lewis R. Eversole